### ISSUE TITLE
Whether the database component should support all databases supported by the TypeOrm?

### ISSUE THREAD

**Issue by felicityin** [ckb-js/kuai#59]
As this [issue](https://github.com/ckb-js/kuai/issues/16) said, the goal of the database layer is to allow dapps to migrate between databases at a lower cost (dapps won't migrate databases often but it's a prominent characteristic of this layer), so it's better to support multi databases, not just PostgreSql.

In addition, we should not decide which database to use for developers. Developers should decide it according to their own scenarios, because there are many factors that will affect the database selection.

**Comment by Keith-CY** [comment]
This issue comes from the discussion in https://github.com/ckb-js/kuai/pull/56#discussion_r1037342877, and I think it covers at least 2 aspects to have consideration:

1. Should the database component be designed to support all databases supported by TypeORM?
2. Should the database component delivered in the MVP support all databases as designed?

---

The first question could be divided into 2 minor questions:

1. Should Kuai consider SQL as its primary support?
2. Should Kuai consider NoSQL as its primary support?

I would refer to the `Store` design in [kuai proposal](https://github.com/ckb-js/topics/blob/add-draft-of-kuai-proposal/README.md) to answer

> The basic function of cells in CKB is storing data. But data are meaningless without schema, so the first basic model introduced by `Kuai` is named `Store` which is used to transform plain data into a structured data with schema, similar to [ORM](https://www.wikiwand.com/en/Object-relational_mapping)

> Note that a `Store` model could be a group of cells matching the same `pattern` and working as an entity, so it could be regarded as a virtual DApp.

From the reference, we can learn that one of kuai's targets is to transform plain data on the chain into **structured** data and use **pattern matching** to group data from various cells into a model. It's a classic scenario of a relational database, so SQL should be considered as the primary support.

Then talk about NoSQL.

Since I cannot recall any cases on the chain that could be featured with NoSQL(massive data, dynamic schema) and we do need **pattern matching**, I would not suggest treating NoSQL as kuai's primary support until a solid use case is proposed.

-----------------

For the second question **"Should the database component delivered in the MVP support all databases as designed?"**

I think it's flexible for developers who are in charge of the database component. If it's quite easy to support all databases as designed, feel free to do it, and just remember to add a document of supported databases. Or we can only enable PostgreSQL for the MVP because we still have a bundle of work.

Besides, the type definition should be shrunk into an explicit range instead of importing `DataSourceOptions` directly unless all databases will be supported instantly. That's the [origin of this discussion](https://github.com/ckb-js/kuai/pull/56/files#r1037342877)
Ref: https://github.com/typeorm/typeorm/blob/62518ae1226f22b2f230afa615532c92f1544f01/src/data-source/DataSourceOptions.ts#L23

----

Now back to the questions in the top message

> As this https://github.com/ckb-js/kuai/issues/16 said, the goal of the database layer is to allow dapps to migrate between databases at a lower cost (dapps won't migrate databases often but it's a prominent characteristic of this layer), so it's better to support multi databases, not just PostgreSql.

**Limiting to several databases** and **migrating between databases** are not contradictory because decoupling the database layer from other layers allows kuai to use various kinds of databases. The range is based on how many will be implemented officially and how many will be implemented by the community(just as [custom couchdb module](https://www.npmjs.com/search?q=nestjs%20couchdb) for nest.js).

And kuai is not coupled with PostgreSQL. Maybe PG is the best choice in MVP, but massive databases will be enabled along with the project's growth.

> In addition, we should not decide which database to use for developers. Developers should decide it according to their own scenarios, because there are many factors that will affect the database selection.

Kuai doesn't decide which one to use, but according to the model, RDBMS is strongly recommended. An opinion is allowed as omakase from developers familiar with CKB.

---

Advice from kuai/dapp developers would help @yanguoyu @PainterPuppets @homura @duanyytop @shaojunda

**Comment by duanyytop** [comment]
I think developers don't care about database selection, flexible data storage and convenient interface query are the most critical, and the source of data is not limited to `cell data` , but also includes `lock script` / `type script` / `witnesses`.

I think that lowering the development threshold is not to give developers the right to choose, but to flexibly provide developers with the data that may need to be stored and queried on CKB.

.bit, UniPass, CoTA, and JoyID all have a large amount of data stored in witnesses, and all need to synchronize, parse and store data from the chain. So I think kuai can help developers provide support at the data storage level so that they can focus more on business development rather than a large number of basic components.

**Comment by felicityin** [comment]
> I think developers don't care about database selection, flexible data storage and convenient interface query are the most critical, and the source of data is not limited to `cell data` , but also includes `lock script` / `type script` / `witnesses`.
> 
> I think that lowering the development threshold is not to give developers the right to choose, but to flexibly provide developers with the data that may need to be stored and queried on CKB.
> 
> .bit, UniPass, CoTA, and JoyID all have a large amount of data stored in witnesses, and all need to synchronize, parse and store data from the chain. So I think kuai can help developers provide support at the data storage level so that they can focus more on business development rather than a large number of basic components.

Do you mean that kuai should only provide developers with the interface of pg database?

**Comment by duanyytop** [comment]
I can't give a suggestion on whether it is PostgreSQL. My suggestion is to choose one for developers to use directly. What I know so far is that most of the MySql is used, and the NoSQL scene has not been seen.

**Comment by yanguoyu** [comment]
I think we should implement the smallest complete framework to run it. And as [duanyytop](https://github.com/duanyytop)'s comments, most developers will not care where to store.
And we can provide a way to override IO interfaces in the future plan.

**Comment by homura** [comment]
I agree that Kuai could provide a default implementation of the storage module and just choose a popular database. 

I understand that Kuai is module oriented rather than interface oriented. For less common requirements, perhaps we can later use documentation that tells developers how to implement their own modules to work with Kuai

Therefore, I personally prefer to support MySQL/MariaDB first, as it is currently the [most popular](https://db-engines.com/en/ranking) open source solution

BTW, I also remember that Kuai means "快(quick)", which means that it helps developers to build dApps quickly, and the rich options may also make developers spend time on choosing a solution

**Comment by felicityin** [comment]
> I agree that Kuai could provide a default implementation of the storage module and just choose a popular database.
> 
> I understand that Kuai is module oriented rather than interface oriented. For less common requirements, perhaps we can later use documentation that tells developers how to implement their own modules to work with Kuai
> 
> Therefore, I personally prefer to support MySQL/MariaDB first, as it is currently the [most popular](https://db-engines.com/en/ranking) open source solution
> 
> BTW, I also remember that Kuai means "快(quick)", which means that it helps developers to build dApps quickly, and the rich options may also make developers spend time on choosing a solution

I see.

**Comment by Keith-CY** [comment]
> I can't give a suggestion on whether it is PostgreSQL. My suggestion is to choose one for developers to use directly. What I know so far is that most of the MySql is used, and the NoSQL scene has not been seen.

🤔 It's the first to know that most of our teams are using MySQL, I thought it was PG because it is used in ckb explorer and mibao

**Comment by duanyytop** [comment]
The aggregators of CoTA and .bit use MySQL.

**Comment by Keith-CY** [comment]
> The aggregators of CoTA and .bit use MySQL.

Good to know that, MySQL should be considered prior to other databases too.

**Comment by Keith-CY** [comment]
It's been confirmed that MySQL and PostgreSQL will be supported first and will be delivered with https://github.com/ckb-js/kuai/pull/56
